services:
  manager:
    depends_on:
      - mongo
      - rabbitmq
    build: ./manager
    environment:
      - SENDER_MESSAGE_CAPACITY=200
      - SENDER_COMMAND_CAPACITY=200
      - MAX_TIMEOUT_STREAK=5
      - PING_TICK_MILLIS=${PING_TICK_MILLIS}
      - WORKERS_AMOUNT=3
      - EXCHANGE_NAME=${EXCHANGE_NAME}
      - MANAGER_QUEUE_NAME=${MANAGER_QUEUE_NAME}
      - DATABASE=${DATABASE}
      - DB_PSWD=${DB_PSWD}
      - DB_USERNAME=${DB_USERNAME}
    volumes:
      - ./manager/src:/manager/src
    ports:
      - "8080:8080"